### ISSUE TITLE
Stale lifecycle phases aren't cleaned up with updated Recipe

### ISSUE THREAD

**Issue by rawalexe** [aws-greengrass/aws-greengrass-lite#746]
## Issue Scenario 

Below is an example of when the issue occurs:

sample_component v1 -> Deployment 1
```yaml
---
...
Manifest:
    - Platform:
        os: linux
        runtime: "aws_nucleus_lite"
      Lifecycle:
        install: "echo Hello World!"
        run: 'while true; do echo "Hello World!" && sleep 1; done'
...
```

Now we do a new deployment which is a revision of the above deployment
sample_component v1.1 -> Deployment 2 
```yaml
---
...
Manifest:
    - Platform:
        os: linux
        runtime: "aws_nucleus_lite"
      Lifecycle:
        # missing install
        # run replaced by startup
        startup: 'while true; do echo "Hello World!" && sleep 1; done'
...
```
